import { IExpenses } from '../expenses.component.interface';

export const EXPENSES_BY_DATE_API: IExpenses[] = [
  {
    id: 1,
    name: 'Lunch at restaurant',
    category: 'Food',
    paymentMethod: 'Cash',
    remarks: 'Paid in cash',
    date: new Date('2024-08-01'),
    amount: 20.5,
  },
  {
    id: 2,
    name: 'Bus ticket',
    category: 'Transportation',
    paymentMethod: 'GCash',
    remarks: 'Round trip',
    date: new Date('2024-08-02'),
    amount: 3.0,
  },
  {
    id: 3,
    name: 'Grocery shopping',
    category: 'Grocery',
    paymentMethod: 'Bank Transfer',
    remarks: 'Weekly groceries',
    date: new Date('2024-08-03'),
    amount: 45.0,
  },
  {
    id: 4,
    name: 'Electric bill',
    category: 'Bills',
    paymentMethod: 'Maya',
    remarks: 'Monthly electricity bill',
    date: new Date('2024-08-04'),
    amount: 75.0,
  },
  {
    id: 5,
    name: 'Coffee',
    category: 'Drinks',
    paymentMethod: 'ShopeePay',
    remarks: 'Morning coffee',
    date: new Date('2024-08-05'),
    amount: 5.0,
  },
  {
    id: 6,
    name: 'Car fuel',
    category: 'Gas',
    paymentMethod: 'SpayLater',
    remarks: 'Full tank',
    date: new Date('2024-08-06'),
    amount: 50.0,
  },
  {
    id: 7,
    name: 'Doctor visit',
    category: 'Health',
    paymentMethod: 'CIMB',
    remarks: 'Routine checkup',
    date: new Date('2024-08-07'),
    amount: 100.0,
  },
  {
    id: 8,
    name: 'Clothes',
    category: 'Shopping',
    paymentMethod: 'Coins.ph',
    remarks: 'New outfit',
    date: new Date('2024-08-08'),
    amount: 120.0,
  },
  {
    id: 9,
    name: 'Flight ticket',
    category: 'Flight',
    paymentMethod: 'Cash',
    remarks: 'Round trip',
    date: new Date('2024-08-09'),
    amount: 200.0,
  },
  {
    id: 10,
    name: 'Game purchase',
    category: 'Gaming',
    paymentMethod: 'Bank Transfer',
    remarks: 'New video game',
    date: new Date('2024-08-18'),
    amount: 60.0,
  },
  {
    id: 11,
    name: 'Laptop repair',
    category: 'Electronics',
    paymentMethod: 'GCash',
    remarks: 'Screen replacement',
    date: new Date('2024-08-18'),
    amount: 150.0,
  },
  {
    id: 12,
    name: 'Movie ticket',
    category: 'Entertainment',
    paymentMethod: 'Maya',
    remarks: 'Movie night',
    date: new Date('2024-08-18'),
    amount: 120000.0,
  },
  {
    id: 13,
    name: 'Dinner with friends',
    category: 'Food',
    paymentMethod: 'ShopeePay',
    remarks: 'Group dinner',
    date: new Date('2024-08-16'),
    amount: 80.0,
  },
  {
    id: 14,
    name: 'Taxi ride',
    category: 'Transportation',
    paymentMethod: 'SpayLater',
    remarks: 'To the airport',
    date: new Date('2024-08-16'),
    amount: 15.0,
  },
];
