export const VIEW_ALL_BILLS_API = [
  {
    id: '1',
    name: 'Laptop',
    term: 8,
    occurrence: 1,
    amount: 200,
    notes: 'Monthly credit card payment',
    dueDate: new Date(2024, 7, 1), // August is month 7 (0-based index)
    isPaid: false,
  },
  {
    id: '2',
    name: 'Mortgage Payment',
    term: 8,
    occurrence: 1,
    amount: 1200,
    notes: 'Monthly mortgage payment',
    dueDate: new Date(2024, 7, 1),
    isPaid: false,
  },
  {
    id: '2',
    name: 'Mortgage Payment',
    term: 8,
    occurrence: 1,
    amount: 1200,
    notes: 'Monthly mortgage payment',
    dueDate: new Date(2024, 7, 1),
    isPaid: false,
  },
  {
    id: '2',
    name: 'Mortgage Payment',
    term: 8,
    occurrence: 1,
    amount: 1200,
    notes: 'Monthly mortgage payment',
    dueDate: new Date(2024, 7, 1),
    isPaid: false,
  },
  {
    id: '2',
    name: 'Mortgage Payment',
    term: 8,
    occurrence: 1,
    amount: 1200,
    notes: 'Monthly mortgage payment',
    dueDate: new Date(2024, 7, 1),
    isPaid: false,
  },
  {
    id: '2',
    name: 'Mortgage Payment',
    term: 8,
    occurrence: 1,
    amount: 1200,
    notes: 'Monthly mortgage payment',
    dueDate: new Date(2024, 7, 1),
    isPaid: false,
  },
  {
    id: '3',
    name: 'Utility Bill  ',
    term: 8,
    occurrence: 1,
    amount: 100,
    notes: 'Monthly utility bill',
    dueDate: new Date(2024, 7, 1),
    isPaid: false,
  },
  {
    id: '4',
    name: 'Car Loan Payment  ',
    term: 8,
    occurrence: 1,
    amount: 350,
    notes: 'Monthly car loan payment',
    dueDate: new Date(2024, 7, 1),
    isPaid: false,
  },
  {
    id: '5',
    name: 'Student Loan Payment  ',
    term: 8,
    occurrence: 1,
    amount: 250,
    notes: 'Monthly student loan payment',
    dueDate: new Date(2024, 8, 1), // September is month 8
    isPaid: false,
  },
  {
    id: '6',
    name: 'Internet Subscription  ',
    term: 8,
    occurrence: 1,
    amount: 60,
    notes: 'Monthly internet subscription fee',
    dueDate: new Date(2024, 8, 1),
    isPaid: false,
  },
  {
    id: '7',
    name: 'Gym Membership  ',
    term: 8,
    occurrence: 1,
    amount: 45,
    notes: 'Monthly gym membership fee',
    dueDate: new Date(2024, 9, 1),
    isPaid: false,
  },
  {
    id: '8',
    name: 'Insurance Premium  ',
    term: 8,
    occurrence: 1,
    amount: 150,
    notes: 'Monthly insurance premium',
    dueDate: new Date(2024, 9, 1),
    isPaid: false,
  },
];

export const VIEW_BILL_BY_NAME_API = [
  {
    id: '14102155',
    name: 'Laptop  ',
    term: 8,
    occurrence: 1,
    amount: 200,
    notes: 'Monthly home credit',
    dueDate: new Date(2024, 1, 25),
    isPaid: true,
  },
  {
    id: '141402156',
    name: 'Laptop  ',
    term: 8,
    occurrence: 1,
    amount: 200,
    notes: 'Monthly home credit',
    dueDate: new Date(2024, 2, 25),
    isPaid: true,
  },
  {
    id: '14102157',
    name: 'Laptop  ',
    term: 8,
    occurrence: 1,
    amount: 200,
    notes: 'Monthly home credit',
    dueDate: new Date(2024, 3, 25),
    isPaid: true,
  },
  {
    id: '14102158',
    name: 'Laptop  ',
    term: 8,
    occurrence: 1,
    amount: 200,
    notes: 'Monthly home credit',
    dueDate: new Date(2024, 4, 25),
    isPaid: true,
  },
  {
    id: '14102159',
    name: 'Laptop  ',
    term: 8,
    occurrence: 1,
    amount: 200,
    notes: 'Monthly home credit',
    dueDate: new Date(2024, 5, 25),
    isPaid: true,
  },
  {
    id: '14102160',
    name: 'Laptop  ',
    term: 8,
    occurrence: 1,
    amount: 200,
    notes: 'Monthly home credit',
    dueDate: new Date(2024, 6, 25),
    isPaid: true,
  },
  {
    id: '14102161',
    name: 'Laptop  ',
    term: 8,
    occurrence: 1,
    amount: 200,
    notes: 'Monthly home credit',
    dueDate: new Date(2024, 7, 25),
    isPaid: false,
  },
  {
    id: '14102162',
    name: 'Laptop  ',
    term: 8,
    occurrence: 1,
    amount: 200,
    notes: 'Monthly home credit',
    dueDate: new Date(2024, 8, 25),
    isPaid: false,
  },
];
